apiVersion: app/v1
kind: Deployment
metadata:
  name: queue-depl
  labels:
    app: queue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queue
  template:
    metadata:
      labels:
        app: queue
    spec:
      containers:
      - name: queue-con
        image: richardchesterwood/k8s-fleetman-queue:release1
        ports:
        - containerPort: 8161
        - containerPort: 61616

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
spec:
  selector:
    app: queue
  ports:
  - protocol: TCP
    port: 8161
    targetPort: 8161
  - protocol: TCP
    port: 61616
    targetPort: 61616