apiVersion: app/v1
kind: Deployment
metadata:
  name: position-simulator-depl
  labels:
    app: position-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: position-simulator
  template:
    metadata:
      labels:
        app: position-simulator
    spec:
      containers:
      - name: position-simulator-con
        image: richardchesterwood/k8s-fleetman-position-simulator:release1

