apiVersion: app/v1
kind: Deployment
metadata:
  name: position-tracker-depl
  labels:
    app: position-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: position-tracker
  template:
    metadata:
      labels:
        app: position-tracker
    spec:
      containers:
      - name: position-tracker-con
        image: richardchesterwood/k8s-fleetman-position-tracker:release1
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-tracker
spec:
  selector:
    app: webapp
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080