apiVersion: app/v1
kind: Deployment
metadata:
  name: webapp-depl
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp-con
        image: richardchesterwood/k8s-fleetman-webapp-angular:release1
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
spec:
  type: LoadBalancer
  selector:
    app: webapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30010